class ChecklistItem {
  final int id;
  final String textEnglish;
  final String textUrdu;
  bool value;
  final bool isAutoGenerated; // ✅ To mark auto-generated precautions

  ChecklistItem({
    required this.id,
    required this.textEnglish,
    required this.textUrdu,
    this.value = false,
    this.isAutoGenerated = false, // Default is false for regular items
  });

  factory ChecklistItem.fromJson(Map<String, dynamic> json) {
    return ChecklistItem(
      id: json['id'],
      textEnglish: json['label_en'], // Updated from text_english
      textUrdu: json['label_ur'],   // Updated from text_urdu
      value: false,
      isAutoGenerated: (json['source'] ?? '').toString().toUpperCase() == 'AUTO',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'label_en': textEnglish,
      'label_ur': textUrdu,
      'value': value ? 'YES' : 'NO',
      'isAutoGenerated': isAutoGenerated,
    };
  }
}

