// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJh-YayGYGR-OFEMc1Oa9UTrXQPjCN6s',
    appId: '1:97210344550:web:f6c16742a03e3a501db9a7',
    messagingSenderId: '97210344550',
    projectId: 'mepco-esafety',
    authDomain: 'mepco-esafety.firebaseapp.com',
    storageBucket: 'mepco-esafety.firebasestorage.app',
    measurementId: 'G-BN4175R0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZt5nFO6OLDQUbbljd9reZyZY8YT_TI4',
    appId: '1:97210344550:android:f600ca0b706323d81db9a7',
    messagingSenderId: '97210344550',
    projectId: 'mepco-esafety',
    storageBucket: 'mepco-esafety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyLBUq9NdLy_Co1PGqlqFqSxToioOxpk',
    appId: '1:97210344550:ios:b3033c3d82fe38611db9a7',
    messagingSenderId: '97210344550',
    projectId: 'mepco-esafety',
    storageBucket: 'mepco-esafety.firebasestorage.app',
    iosBundleId: 'com.example.mepcoEsafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyLBUq9NdLy_Co1PGqlqFqSxToioOxpk',
    appId: '1:97210344550:ios:b3033c3d82fe38611db9a7',
    messagingSenderId: '97210344550',
    projectId: 'mepco-esafety',
    storageBucket: 'mepco-esafety.firebasestorage.app',
    iosBundleId: 'com.example.mepcoEsafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJh-YayGYGR-OFEMc1Oa9UTrXQPjCN6s',
    appId: '1:97210344550:web:85c63b76c23859211db9a7',
    messagingSenderId: '97210344550',
    projectId: 'mepco-esafety',
    authDomain: 'mepco-esafety.firebaseapp.com',
    storageBucket: 'mepco-esafety.firebasestorage.app',
    measurementId: 'G-7BGEYD78NK',
  );
}
